### ISSUE TITLE
Room Presence not changing(FIXED)

### ISSUE THREAD

**Issue by ikirt** [jxlarrea/ha-bt-proximity#1]
Hello,

I want to start off by saying great project !

I found an issue with the following line of code:

{% if not (states('sensor.mike_office_proximity') == 'unknown') and (states('sensor.mike_office_proximity')|int > -5) %}

With this logic I couldn't get the sensor to trigger till I looked closer at this line, noticing that it should be <(less than) as I with telemetry, stronger the signal the lower the number is.

After changing the line to this:

{% if not (states('sensor.mike_office_proximity') == 'unknown') and (states('sensor.mike_office_proximity')|int < -5) %}

I'm finding the sensor is now updating when bluetooth telemetry strength is(stronger) less than -5.

**Comment by jxlarrea** [comment]
Hey,

Actually, the proximity value ranges from 0 (strongest) to -100 (weakest/undetectable). So > (greater than) in that if statement is correct. 

Check the value of sensor.mike_office_proximity with the phone right next to your Raspberry Pi. Then further away.

**Comment by ikirt** [comment]
My bad, you're right, with my testing I was seeing the opposite results, for some reason the when I am close to the pi the rssi signal strength dropped.

**Comment by bachoo786** [comment]
How quickly does the pi pick up the change from one room to another? Is it seconds or milliseconds?
